hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "kde")
hl.env("EDITOR", "nvim")
hl.env("BROWSER", "firefox-developer-edition")
hl.env("NAME", "Matthew Varble")
hl.env("EMAIL", "matthew@rodent.club")
hl.env("TZ", "US/Pacific")
hl.env("CARGO_TARGET_DIR", "$HOME/.cargo-target")
