live_config_reload: true

window:
  dimensions:
   columns: 120
   lines: 40
  padding:
    x: 1
    y: 1
  position:
    x: 100
    y: 100
  opacity: 0.9

font:
  normal:
    family: SF Mono
    style: Regular
  bold:
    family: SF Mono
    style: Bold
  italic:
    family: SF Mono
    style: Medium Italic
  bold_italic:
    family: SF Mono
    style: Bold Italic
  size: 10

draw_bold_text_with_bright_colors: false

cursor:
  style:
    shape: Block
    blinking: Off

shell:
  program: fish
  args:
    - -l
    - -c
    - tmux
