# set prefix to CTRL-b
set-option -g prefix C-b
bind-key C-b send-prefix

# history limit
set -g history-limit 1000000

# use <prefix> O/U keys to create panes
bind o split-window -h -c '#{pane_current_path}'
bind u split-window -v -c '#{pane_current_path}'

# use <prefix> "vim" keys to switch panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# use <prefix> n to create a new window at same path
bind t new-window -c '#{pane_current_path}'

# use CTRL-<number>  keys to move between windows
set -g base-index 1
set -g pane-base-index 1

# use <prefix> ;/' to switch between windows
bind n select-window -t :-1
bind m select-window -t :+1

# use <prefix> up/down to move windows
bind Up swap-window -t -1 \; select-window -t -1
bind Left swap-window -t -1 \; select-window -t -1
bind Down swap-window -t +1 \; select-window -t +1
bind Right swap-window -t +1 \; select-window -t +1

# escape time
set-option -sg escape-time 250

# set focus events on
set-option -g focus-events on

# move around with vim keys
set -g mode-keys vi
set -g status-keys vi
bind c copy-mode

# reset the numbers with <prefix> Space
bind Space movew -r

# select panes with mouse
set -g mouse on
set-option -s set-clipboard off

# use fish
set-option -g default-shell /usr/bin/fish

# bottom bar
set -g status on
set -g status-interval 1
set -g status-left '[#H:#S] '
set -g status-left-length 20
set -g status-style 'bg=black,fg=default'
set -g status-right ' #{?client_prefix,#[reverse]<Prefix>#[noreverse] ,}%Y-%m-%d, %H:%M:%S'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tinted-theming/tinted-tmux'

# yank config
set -g @yank_selection_mouse 'clipboard'
set -g @yank_action 'copy-pipe'
set -g @yank_with_mouse 'on'

# TERM
set -g default-terminal "tmux-256color"
set -ag terminal-features ",*:RGB"

# coloring handled by tinty
set -g allow-passthrough on

# initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# set active color to blue
set -g mode-style 'bg=blue,fg=black'
set -g pane-active-border-style 'fg=blue'
