# use CTRL-* keys to create panes
bind -n C-O split-window -h -c '#{pane_current_path}'
bind -n C-U split-window -v -c '#{pane_current_path}'

# use CTRL-vim keys to switch panes
#bind -n C-H select-pane -L
#bind -n C-J select-pane -D 
#bind -n C-K select-pane -U
#bind -n C-L select-pane -R

# use CTRL-vim keys to move between windows
bind -n C-L next-window
bind -n C-H previous-window

# use CTRL-n to create a new window
bind -n C-N new-window

# use <prefix>-r to rename window (instead of <prefix> $)
bind r command-prompt -I 'rename-window '

# use <prefix>-t to rename session
bind t command-prompt -I 'rename-session '

# select panes with mouse
set -g mouse on
set-option -s set-clipboard off

# use fish
set-option -g default-shell /usr/bin/zsh

# bottom bar
set -g status on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tinted-theming/base16-tmux'

# yank config
set -g @yank_selection_mouse 'clipboard'
set -g @yank_action 'copy-pipe-and-cancel'
set -g @yank_with_mouse 'on'

# base16 config
set -g allow-passthrough 1
set -g @colors-base16 'ocean'

# initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# highlight/active colors
set -g mode-style 'bg=blue,fg=black'
set -g pane-active-border-style 'fg=blue'
