# zplug
source ~/.zplug/init.zsh
zplug "mafredri/zsh-async", from:github, defer:0
zplug "zsh-users/zsh-autosuggestions", from:github, defer:2
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:2
zplug "lib/git", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "plugin/git", from:oh-my-zsh
zplug "chriskempson/base16-shell", from:github
zplug "bobsoppe/zsh-ssh-agent", from:github, use:ssh-agent.zsh
zplug load

# theme
setopt PROMPT_SUBST
PROMPT='%{$fg_no_bold[cyan]%}%n%{$reset_color%}@%{$fg_no_bold[magenta]%}18.04'
PROMPT+=' %{$fg_no_bold[blue]%}%(4~|%-1~/…/%2~|%3~)%{$reset_color%}» '
RPROMPT='$(git_prompt_info)'
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_no_bold[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg_bold[yellow]%} ✗"

# git style
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '(%b)'

# https://unix.stackexchange.com/questions/367693/fish-like-argument-completion-search-in-zsh
zmodload zsh/complist
zstyle ':completion:*' menu yes select
bindkey -M menuselect '^[[Z' reverse-menu-complete

# https://superuser.com/questions/560864/zsh-history-up-arrow-history-completion-not-working
if [[ "${terminfo[kcuu1]}" != "" ]]; then
    autoload -U up-line-or-beginning-search
    zle -N up-line-or-beginning-search
    bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi
if [[ "${terminfo[kcud1]}" != "" ]]; then
    autoload -U down-line-or-beginning-search
    zle -N down-line-or-beginning-search
    bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi

# https://askubuntu.com/questions/902729/why-isnt-my-zsh-ls-colorful
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
		test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
		alias ls='ls --color=auto'
		alias dir='dir --color=auto'
		alias vdir='vdir --color=auto'
		alias grep='grep --color=auto'
		alias fgrep='fgrep --color=auto'
		alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# aliases
export EDITOR=nvim
alias oldvim=vim
alias vi=nvim
alias vim=nvim
alias ll="ls -al"

# update PATH
PATH+=:~/.node-v$NODE_VERSION/bin
PATH+=:~/.julia-$JULIA_VERSION/bin
PATH+=:~/.blender-$BLENDER_VERSION
PATH+=:~/.nvim/bin
PATH+=:~/.cargo/bin
PATH+=:~/.npm-global/bin
PATH+=:~/.local/bin
export PATH

# ROS 2 stuff
source /opt/workspace/ros2/galactic/install/setup.zsh
source /usr/share/colcon_cd/function/colcon_cd.sh
source /opt/workspace/ros2_ext/plotjuggler/install/local_setup.zsh
export _colcon_cd_root=/opt/workspace/ros2/galactic/install
source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.zsh
eval "$(register-python-argcomplete3 ros2)"
eval "$(register-python-argcomplete3 colcon)"
