[General]
hotkey=Alt+Space
showTray=true

[org.albert.extension.applications]
enabled=true

[org.albert.extension.files]
enabled=true
filters=inode/directory, application/*, image/*
follow_symlinks=true

[org.albert.extension.websearch]
enabled=true

[org.albert.frontend.widgetboxmodel]
alwaysOnTop=true
clearOnHide=false
displayIcons=true
displayScrollbar=false
displayShadow=true
hideOnClose=false
hideOnFocusLoss=true
itemCount=5
showCentered=true
theme=Numix Rounded
windowPosition=@Point(608 283)
