#!/bin/sh

#
# set display
#
xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --primary --output DVI-I-0 --mode 1600x1200 --right-of HDMI-0

#
# set keyboard options
#
xset r rate 250 100
setxkbmap -option caps:super

#
# set wacom to the appropriate display
#
xsetwacom set "22" MapToOutput HEAD-1
xsetwacom set "18" MapToOutput HEAD-1
xsetwacom set "17" MapToOutput HEAD-1

#
# set environment variables
#
MONITOR_MAIN="HDMI-0"
export MONITOR_MAIN
MONITOR_ALT="DVI-I-0"
export MONITOR_ALT

#
# TODO: configure workspaces depending on monitors
#
bspc monitor HDMI-0 -d 
bspc monitor DVI-I-0 -d     ...

#
# configure window geometry
#
bspc config border_width         3
bspc config window_gap           3
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#
# configure rules for specific apps
#
bspc rule -a ulauncher focus=on
bspc rule -a polybar border=off manage=off
bspc rule -a Alacritty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Zathura state='tiled' desktop='^3'
bspc rule -a okular state='tiled' desktop='^3'
bspc rule -a Xournalpp state='tiled' desktop='^4'

#
# configure rules for monitors
#
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

#
# launch all the goodies
#
sxhkd &
picom &
ulauncher --hide-window --no-window-shadow &
nitrogen --restore &
polybar-msg cmd quit &
polybar --reload ratcage1 2>&1 | tee -a /tmp/polybar-1.log & disown
polybar --reload ratcage2 2>&1 | tee -a /tmp/polybar-2.log & disown
dropbox start &
