#!/bin/sh

#
# set display
#
xrandr --output eDP-1 --mode 1366x768 --primary 

#
# set environment variables
#
MONITOR_MAIN="eDP-1"
export MONITOR_MAIN

#
# set keyboard options
#
xset r rate 250 100
setxkbmap -option caps:super

#
# TODO: configure workspaces depending on monitors
#
bspc monitor $MONITOR_MAIN -d    etc.

#
# configure window geometry
#
bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#
# configure rules for specific apps
#
bspc rule -a albert focus=on border=off
bspc rule -a polybar border=off manage=off
bspc rule -a Alacritty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Zathura state='tiled' desktop='^3'
bspc rule -a Evince state='tiled' desktop='^3'
bspc rule -a okular state='tiled' desktop='^3'

#
# launch all the goodies
#
sxhkd &
picom &
albert &>/tmp/albert.log & disown
nitrogen --restore &
polybar-msg cmd quit &
polybar --reload ratbutt 2>&1 | tee -a /tmp/polybar.log & disown
dropbox start &
